Fixing EC2 CPU/Memory load integration tests. Added skip for other compute broken tests.

diff --git a/documents/util/ec2/run_cpu_stress/2020-07-28/Documents/AutomationDocument.yml b/documents/util/ec2/run_cpu_stress/2020-07-28/Documents/AutomationDocument.yml
--- a/documents/util/ec2/run_cpu_stress/2020-07-28/Documents/AutomationDocument.yml
+++ b/documents/util/ec2/run_cpu_stress/2020-07-28/Documents/AutomationDocument.yml
@@ -1,45 +1,96 @@
-#
-# Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
-#
-# Permission is hereby granted, free of charge, to any person obtaining a copy of this
-# software and associated documentation files (the "Software"), to deal in the Software
-# without restriction, including without limitation the rights to use, copy, modify,
-# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
-# permit persons to whom the Software is furnished to do so.
-#
-# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
-# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
-# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
-# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
-# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
-# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
-#
+# Content taken from AWS FIS:
+# https://code.amazon.com/packages/AWSFIS-SSMDocuments/blobs/heads/aws_fis_release_v1.1/--/Command/AWSFIS-Run-CPU-Stress/Documents/AWSFIS-Run-CPU-Stress.yml
+# NOTE: Once AWS FIS team will publish documents we will replace it with public document: https://issues.amazon.com/issues/Digito-2004
 ---
-description: Run a CPU stress on EC2 instance
+description: |
+  ### Document name - AWSFIS-Run-CPU-Stress
+
+  ## What does this document do?
+  It runs CPU stress on an instance via stress-ng tool.
+
+  ## Input Parameters
+  * DurationSeconds: (Required) The duration - in seconds - of the CPU stress.
+  * CPU: Specify the number of CPU stressors to use (default 0 = all)
+  * InstallDependencies: If set to True, Systems Manager installs the required dependencies on the target instances. (default True)
+
+  ## Output Parameters
+  None.
+
 schemaVersion: '2.2'
 parameters:
-  Duration:
+  DurationSeconds:
     type: String
-    description: (Optional) The duration of the attack in seconds
-    default: '300'
-  CpuLoadPercentage:
+    description: "(Required) The duration - in seconds - of the CPU stress."
+    allowedPattern: "^[0-9]+$"
+  CPU:
     type: String
-    description: (Optional) CPU load percentage
-    default: "1"
-  NumCpuCores:
+    description: 'Specify the number of CPU stressors to use (default: 0 which means "all CPUs")'
+    default: "0"
+    allowedPattern: "^[0-9]+$"
+  LoadPercent:
     type: String
-    description: (Optional) Number of CPU cores to be impacted (default 0 - all)
-    default: '0'
+    description: 'Specify the target CPU load percentage. Valid values are between 0 (no load) and 100 (full load) (default: 100)'
+    default: "100"
+    allowedPattern: "^(100|[1-9]?[0-9])$"
+  InstallDependencies:
+    type: String
+    description: 'If set to True, Systems Manager installs the required dependencies on the target instances (default: True)'
+    default: 'True'
+    allowedValues:
+      - 'True'
+      - 'False'
 mainSteps:
-- action: aws:runShellScript
-  name: ExecuteStressNg
-  precondition:
-    StringEquals:
-      - platformType
-      - Linux
-  inputs:
-    runCommand:
-    # https://www.mankier.com/1/stress-ng#Examples
-    - "sudo amazon-linux-extras install epel -y"
-    - "sudo yum install stress-ng -y"
-    - "stress-ng --cpu {{ NumCpuCores }} -l {{ CpuLoadPercentage }} --cpu-method matrixprod -t {{ Duration }}s"
+  - action: aws:runShellScript
+    name: InstallDependencies
+    precondition:
+      StringEquals:
+        - platformType
+        - Linux
+    description: |
+      ## Parameter: InstallDependencies
+      If set to True, this step installs the required dependecy via operating system's repository. It supports both
+      Debian (apt) and CentOS (yum) based package managers.
+    inputs:
+      runCommand:
+        - |
+          #!/bin/bash
+          if  [[ "{{ InstallDependencies }}" == True ]] ; then
+            if [[ "$( which stress-ng 2>/dev/null )" ]] ; then echo Dependency is already installed. ; exit ; fi
+            echo "Installing required dependencies"
+            if [ -f  "/etc/system-release" ] ; then
+              if cat /etc/system-release | grep -i 'Amazon Linux' ; then
+                # Use amazon-linux-extras if available (Amazon Linux 2). Don't need it otherwise (Amazon Linux 1)
+                which amazon-linux-extras 2>/dev/null 1>&2 && sudo amazon-linux-extras install testing
+                sudo yum -y install stress-ng
+              else
+                echo "There was a problem installing dependencies."
+                exit 1
+              fi
+            elif cat /etc/issue | grep -i Ubuntu ; then
+              sudo apt-get update -y
+              sudo DEBIAN_FRONTEND=noninteractive sudo apt-get install -y stress-ng
+            else
+              echo "There was a problem installing dependencies."
+              exit 1
+            fi
+          fi
+  - action: aws:runShellScript
+    name: ExecuteStressNg
+    precondition:
+      StringEquals:
+        - platformType
+        - Linux
+    description: |
+      ## Parameters: DurationSeconds and CPU
+      This step will stress the specified CPU number - or all CPUs if set to 0 (zero) - for the specified Duration time
+      in seconds.
+    inputs:
+      maxAttempts: 1
+      runCommand:
+        - |
+          if [ {{ DurationSeconds }} -lt 1 ] || [ {{ DurationSeconds }} -gt 43200 ] ; then echo DurationSeconds parameter value must be between 1 and 43200 && exit 1; fi
+          if [ {{ LoadPercent }} -lt 0 ] || [ {{ LoadPercent }} -gt 100 ] ; then echo LoadPercent parameter value must be between 0 and 100 && exit 1; fi
+          pgrep stress-ng && echo Another stress-ng command is running, exiting... && exit
+          echo Initiating CPU stress for {{ DurationSeconds }} seconds...
+          stress-ng --cpu {{ CPU }} --cpu-method matrixprod -t {{ DurationSeconds }}s --cpu-load {{ LoadPercent }}
+          echo Finished CPU stress.
diff --git a/documents/util/ec2/run_memory_stress/2020-07-28/Documents/AutomationDocument.yml b/documents/util/ec2/run_memory_stress/2020-07-28/Documents/AutomationDocument.yml
--- a/documents/util/ec2/run_memory_stress/2020-07-28/Documents/AutomationDocument.yml
+++ b/documents/util/ec2/run_memory_stress/2020-07-28/Documents/AutomationDocument.yml
@@ -1,44 +1,94 @@
-#
-# Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
-#
-# Permission is hereby granted, free of charge, to any person obtaining a copy of this
-# software and associated documentation files (the "Software"), to deal in the Software
-# without restriction, including without limitation the rights to use, copy, modify,
-# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
-# permit persons to whom the Software is furnished to do so.
-#
-# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
-# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
-# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
-# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
-# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
-# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
-#
+# Content taken from AWS FIS: https://code.amazon.com/packages/AWSFIS-SSMDocuments/blobs/heads/aws_fis_release_v1.1/--/Command/AWSFIS-Run-Memory-Stress/Documents/AWSFIS-Run-Memory-Stress.yml
+# NOTE: Once AWS FIS team will publish documents we will replace it with public document: https://issues.amazon.com/issues/Digito-2004
 ---
-description: Run a Memory stress on EC2 instance
+description: |
+  ### Document name - AWSFIS-Run-Memory-Stress
+
+  ## What does this document do?
+  It runs memory stress on an instance via stress-ng tool.
+
+  ## Input Parameters
+  * DurationSeconds: (Required) The duration - in seconds - of the memory stress.
+  * Workers: The number of virtual memory stressors (default: 1).
+  * Percent: The percentage of virtual memory to use (required).
+  * InstallDependencies: If set to True, Systems Manager installs the required dependencies on the target instances. (default: True).
+
+  ## Output Parameters
+  None.
+
 schemaVersion: '2.2'
 parameters:
-  Duration:
+  DurationSeconds:
     type: String
-    description: (Required) The duration of the attack in seconds.
-    default: '300'
-  MemoryLoadPercentage:
+    description: "(Required) The duration - in seconds - of the memory stress."
+    allowedPattern: "^[0-9]+$"
+  Workers:
     type: String
-    description: (Required) Memory load percentage.
-  Vm:
+    description: "The number of virtual memory stressors (default: 1)."
+    default: "1"
+    allowedPattern: "^[0-9]+$"
+  Percent:
     type: String
-    description: (Optional) Number of VM stressors.
-    default: '1'
+    description: "The percentage of virtual memory to use (required)."
+    allowedPattern: "^[0-9]+$"
+  InstallDependencies:
+    type: String
+    description: "If set to True, Systems Manager installs the required dependencies on the target instances. (default: True)."
+    default: 'True'
+    allowedValues:
+      - 'True'
+      - 'False'
 mainSteps:
-- action: aws:runShellScript
-  name: ExecuteStressNg
-  precondition:
-    StringEquals:
-      - platformType
-      - Linux
-  inputs:
-    runCommand:
-    # https://www.mankier.com/1/stress-ng#Examples
-    - "sudo amazon-linux-extras install epel -y"
-    - "sudo yum install stress-ng -y"
-    - "stress-ng --vm {{ Vm }} --vm-bytes {{ MemoryLoadPercentage }}% -t {{ Duration }}s"
+  - action: aws:runShellScript
+    name: InstallDependencies
+    precondition:
+      StringEquals:
+        - platformType
+        - Linux
+    description: |
+      ## Parameter: InstallDependencies
+      If set to True, this step installs the required dependecy via operating system's repository. It supports both
+      Debian (apt) and CentOS (yum) based package managers.
+    inputs:
+      runCommand:
+        - |
+          #!/bin/bash
+          if  [[ "{{ InstallDependencies }}" == True ]] ; then
+            if [[ "$( which stress-ng 2>/dev/null )" ]] ; then echo Dependency is already installed. ; exit ; fi
+            echo "Installing required dependencies"
+            if [ -f  "/etc/system-release" ] ; then
+              if cat /etc/system-release | grep -i 'Amazon Linux' ; then
+                # Use amazon-linux-extras if available (Amazon Linux 2). Don't need it otherwise (Amazon Linux 1)
+                which amazon-linux-extras 2>/dev/null 1>&2 && sudo amazon-linux-extras install testing
+                sudo yum -y install stress-ng
+              else
+                echo "There was a problem installing dependencies."
+                exit 1
+              fi
+            elif cat /etc/issue | grep -i Ubuntu ; then
+              sudo apt-get update -y
+              sudo DEBIAN_FRONTEND=noninteractive sudo apt-get install -y stress-ng
+            else
+              echo "There was a problem installing dependencies."
+              exit 1
+            fi
+          fi
+  - action: aws:runShellScript
+    name: ExecuteStressNg
+    precondition:
+      StringEquals:
+        - platformType
+        - Linux
+    description: |
+      ## Parameters: DurationSeconds, Workers and Percent
+      This step will run a memory stress test on the instance for the specified DurationSeconds time.
+      It will start `Workers` number of workers, using `Percent` of the total available memory.
+    inputs:
+      maxAttempts: 1
+      runCommand:
+        - |
+          if [ {{ DurationSeconds }} -lt 1 ] || [ {{ DurationSeconds }} -gt 43200 ] ; then echo DurationSeconds parameter value must be between 1 and 43200 && exit; fi
+          pgrep stress-ng && echo Another stress-ng command is running, exiting... && exit
+          echo Initiating memory stress for {{ DurationSeconds }} seconds, {{ Workers }} workers, using {{ Percent }} percent of total available memory...
+          stress-ng --vm {{ Workers }} --vm-bytes {{ Percent }}% -t {{ DurationSeconds }}s
+          echo Finished memory stress.
